[[example]]
name = "newest"
required-features = [ "tokio",]

[package]
name = "debbugs"
version = "0.1.1"
edition = "2021"
authors = [ "Jelmer Vernooĳ <jelmer@jelmer.uk>",]
repository = "https://github.com/jelmer/debbugs-rs"
description = "Debian Bugtracking System API client"
readme = "README.md"
license = "Apache-2.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy-regex = "3.0.2"
log = "0.4.20"
maplit = "1.0.2"
reqwest = "0.11"
xmltree = "0.10.3"

[features]
blocking = [ "reqwest/blocking",]
default = [ "blocking", "tokio", "mailparse",]
tokio = [ "dep:tokio",]
mailparse = [ "dep:mailparse",]

[dependencies.mailparse]
version = "0.14.0"
optional = true

[dependencies.env_logger]
version = "0.10.0"
optional = true

[dependencies.tokio]
version = "1"
optional = true
features = [ "full",]
